/*
 * Copyright 2012 - 2013 Herb Bowie
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.powersurgepub.linktweaker;

  import com.powersurgepub.psutils.*;
  import com.powersurgepub.xos2.*;
  import java.io.*;
  import javax.swing.*;

/**
   Favorites Preferences for URL Union.

   @author Herb Bowie
 */
public class TweakerPrefs
    extends javax.swing.JPanel {

  // Prefs explicitly set by the user in this window
  public static final String REDIRECT_URL               = "redirect-url";
  public static final String PREFS_TAB_NAME             = "Link Tweaker";

  // Other prefs used by LinkTweaker
  public static final String PREFS_LEFT    = "left";
  public static final String PREFS_TOP     = "top";
  public static final String PREFS_WIDTH   = "width";
  public static final String PREFS_HEIGHT  = "height";

  private ProgramVersion    programVersion = ProgramVersion.getShared();

  private boolean           setupComplete = false;

  /** Creates new form FavoritesPrefs */
  public TweakerPrefs() {

    initComponents();
    
    redirectTextArea.setText(UserPrefs.getShared().getPref(REDIRECT_URL, ""));

    setupComplete = true;
  }
  
  public String getRedirectURL () {
    return redirectTextArea.getText();
  }

  public void savePrefs() {
    UserPrefs.getShared().setPref(REDIRECT_URL, redirectTextArea.getText());
  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    redirectLabel = new javax.swing.JLabel();
    redirectScrollPane = new javax.swing.JScrollPane();
    redirectTextArea = new javax.swing.JTextArea();
    filler01 = new javax.swing.JLabel();

    setLayout(new java.awt.GridBagLayout());

    redirectLabel.setText("Redirect URL:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    add(redirectLabel, gridBagConstraints);

    redirectTextArea.setColumns(40);
    redirectTextArea.setLineWrap(true);
    redirectTextArea.setRows(5);
    redirectScrollPane.setViewportView(redirectTextArea);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridheight = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    add(redirectScrollPane, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 0.5;
    add(filler01, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel filler01;
  private javax.swing.JLabel redirectLabel;
  private javax.swing.JScrollPane redirectScrollPane;
  private javax.swing.JTextArea redirectTextArea;
  // End of variables declaration//GEN-END:variables

}
